server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: render-service-route
          uri: lb://render-service
          predicates:
            - Path=/render/**
          filters:
            - StripPrefix=1
